---
new_app:
# Ex:
# If you need configure new app repeat block above new_app variable.
  # app_1:
  #   name: "api_1"
  #   port_front: 8070
  #   port_back: 30870
  #   backend: {
  #     "hostname_1": "10.0.0.1",
  #     "hostname_2": "172.16.0.1",
  #     "hostname_3": "192.168.0.1"
  #   }
  kube-apiserver:
    name: "kube-apiserver"
    port_front: 6443
    port_back: 6443
    backend: {
      "kubernetes-master-1": "172.16.29.11",
      "kubernetes-master-2": "172.16.29.12",
      "kubernetes-master-3": "172.16.29.13",
    }