---
kind: pipeline
type: docker
name: jenkins

steps:
  - name: infrastructure/configure
    image: fabianoflorentino/ansible
    commands:
      - cd ./infrastructure/configure
      - ansible-playbook -i inventorie/jenkins/hosts.yml -u root -e "ansible_ssh_pass=$ROOT_PWD" servers.yml
