all:
  vars:
    # Virtual IP for high avalibility with keepalived.
    virtual_ipaddress: ""
    # Hostname for first haproxy service, use the same hostname in inventory_hostname.
    # Ex:
    # haproxy_master: "haproxy-1"
    haproxy_master: ""
    # Select one algorithm for load balance: first, leastconn, static-rr or roundrobin.
    balance_algorithm: ""
    # Select one mode for HAProxy: http or tcp
    haproxy_mode: ""
    # Domain used in infraestructure
    my_domain: ""    
  children:
    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 1.2.3.4 # IP do Servidor 1
        haproxy-2:
          ansible_host: 1.2.3.4 # IP do Servidor 2