all:
  vars:
    # Virtual IP for high avalibility with keepalived.
    virtual_ipaddress: ""
    # Interface for Virtual IP
    inet: ""
    # Hostname for first haproxy service, use the same hostname in inventory_hostname.
    # Ex:
    # haproxy_master: "haproxy-1"
    haproxy_master: ""
    # Select one algorithm for load balance: first, leastconn, static-rr or roundrobin.
    balance_algorithm: ""
    # Select one mode for HAProxy: http or tcp
    haproxy_mode: ""
    # Domain used in infraestructure
    my_domain: "" 
  new_app:
  # Ex:
  # If you need configure new app repeat block above new_app variable.
    # app_1:
    #   name: "api_1"
    #   port_front: 8070
    #   port_back: 30870
    #   backend: {
    #     "hostname_1": "10.0.0.1",
    #     "hostname_2": "172.16.0.1",
    #     "hostname_3": "192.168.0.1"
    #   }   
    app_1:
      name: "api_1"
      port_front: 8070
      port_back: 30870
      backend: {
        "hostname_1": "10.0.0.1",
        "hostname_2": "172.16.0.1",
        "hostname_3": "192.168.0.1"
      }
  children:
    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 1.2.3.4 # IP do Servidor 1
        haproxy-2:
          ansible_host: 1.2.3.4 # IP do Servidor 2