---

master_node: "true"
data_node: "false"
ingest_node: "false"

discovery_zen_minimum_master_nodes: "2"

path_repo: "/backup/elasticsearch/lab"

action_auto_create_index: "true"

network_host: 0.0.0.0
http_port: 9200

elasticsearch_jvm:
  jvm_xms: "1g"
  jvm_xmx: "1g"
