all:
  children:
    masters:
      vars:
        k8s_master_node_ip: 1.2.3.4
        k8s_api_secure_port: 6443
      hosts:
        kubernetes-1:
          ansible_host: 1.2.3.4
    workers:
      vars:
        k8s_master_node_ip: 1.2.3.4
        k8s_api_secure_port: 6443
      hosts:
        kubernetes-2:
          ansible_host: 1.2.3.4
        kubernetes-3:
          ansible_host: 1.2.3.4