---
- name: Criando Grupo de Serviço
  group:
    name: sre
    state: present

- name: Criando Usuário de Serviço
  user:
    name: ansible
    state: present
    generate_ssh_key: yes
    shell: /bin/bash
    append: yes
    groups: ["sre"]

- name: Adicionando o Grupo de Serviço ao Sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    backup: yes
    owner: root
    mode: "0644"
    validate: /usr/sbin/visudo -cf %s

- name: Configurando a Chave SSH Publica no arquivo de Chaves Autorizadas
  template:
    src: authorized_keys.j2
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: "0644"