---
helm_url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
helm_url_repo: https://kubernetes-charts.storage.googleapis.com

prometheus_operator: "--set prometheusOperator.createCustomResource=false prometheus-operator stable/prometheus-operator"