#
# This is an example file, fill in your infrastructure information.
#
---
all:
  hosts:
    elk-1:
      ansible_host: 192.168.165.162
    elk-2:
      ansible_host: 192.168.165.163
    elk-3:
      ansible_host: 192.168.165.164
    elk-4:
      ansible_host: 192.168.165.165
  vars:
    ssh_key:
      - ""
    cluster_mode: "true"
    cluster_name: "elk-stack"
    node_attr_rack: "dc1"
    node_of_cluster:
      elk-1:
        host_ip: "192.168.165.158"
        host_name: "elk-1"
      elk-2:
        host_ip: "192.168.165.159"
        host_name: "elk-2"
      elk-3:
        host_ip: "192.168.165.160"
        host_name: "elk-3"
      elk-4:
        host_ip: "192.168.165.161"
        host_name: "elk-4"
    action_auto_create_index: "true"
    network_host: 0.0.0.0
    http_port: 9200
    elasticsearch_jvm:
      jvm_xms: "1g"
      jvm_xmx: "1g"
    path_repo: "/backup/elasticsearch/lab"
  children:
    es_master_node:
      hosts:
        elk-1:
        elk-2:
      vars:
        master_node: "true"
        data_node: "false"
        ingest_node: "false"
        discovery_zen_minimum_master_nodes: "2"
        action_auto_create_index: "true"
    es_data_node:
      hosts:
        elk-3:
        elk-4:
      vars:
        data_node: "true"
    kibana:
      hosts:
        elk-1:
      vars:
        server_port: "5601"
        server_host: 0.0.0.0
        server_name: "kibana"
        elasticsearch_hosts:
          - "http://{{ inventory_hostname }}:9200"
    logstash:
      hosts:
        elk-2:
      vars:
        node_of_cluster:
          elk-1:
            host_ip: "192.168.165.158"
            host_name: "elk-1"
          elk-2:
            host_ip: "192.168.165.159"
            host_name: "elk-2"
        config_reload_automatic: "false"
        config_reload_interval: "3s"
        pipeline_workers: "1"
        http_host: "0.0.0.0"
        logstash_http_port: "9600"
        logstash_jvm:
          jvm_xms: "512m"
          jvm_xmx: "512m"
