---
- name: Clean YUM
  shell: |
    yum clean all
    rm -rf /var/cache/yum/*
  args:
    warn: false
  register: yum_clean

- name: "Configure GPG KEY"
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: "Configure repository"
  yum_repository:
    name: jenkins
    description: Jenkins is a self-contained, open source automation server
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes

- name: "Install Packages"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - jenkins

- name: "Inicialize systemd services"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - jenkins

- name: "Verify if initialAdminPassword is seted."
  stat: 
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: initialAdminPassword

- name: "Register initialAdminPassword"
  shell: |
    cat /var/lib/jenkins/secrets/initialAdminPassword
  register: admin_password
  when: initialAdminPassword.stat.exists == true

- name: "View initialAdminPassword"
  debug:
    msg: "{{ admin_password.stdout }}"
  when: initialAdminPassword.stat.exists == true