---
- name: Atualizando o Hostname dos Servidores
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Configure GPG KEY for Elastic Repository"
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: "Elastic Repository"
  yum_repository:
    name: "Elastic"
    description: "Elastic repository for 7.x packages"
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    enabled: yes
    gpgcheck: yes

- name: Atualizando /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['inventory_hostname'] }}"
  loop: "{{ groups['all'] }}"

- name: "Packages for ELK Stack"
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.to_install }}"