---

- name: "Configurando SSH para os novos servidores virtuais"
  hosts:
    - servers
  gather_facts: False
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'    
  roles:
    - {role: ssh, tags: "ssh"}