---
- name: Ajustando o Hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Atualizando /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['inventory_hostname'] }}"
  loop: "{{ groups['all'] }}"

- name: Verificando pre requisitos
  package_facts:
    manager: auto

- name: Preparando o Sistema Operacional
  block:      
    - name: Atualizando o Sistema
      yum:
        name: "*"
        state: latest
      when:
        - (update_system == true)

    - name: Verificando se o repositório Docker existe
      stat:
        path: "{{ path_docker_repo }}"
      register: docker_repo

    - name: Habilitando o Repositório do Docker
      yum_repository:
        name: docker
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        file: docker
      when: 
        - (docker_repo.stat.exists == false)

    - name: Verificando se o repositório Kubernetes existe
      stat:
        path: "{{ path_kubernetes_repo }}"
      register: kubernetes_repo

    - name: Habilitando o Repositório do Kubernetes
      yum_repository:
        name: kubernetes
        description: kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        file: kubernetes
      when: 
        - (kubernetes_repo.stat.exists == false)

    - name: Instalando pacotes essenciais
      yum:
        name:  "{{ packages.to_install }}"
        state: present

    - name: Pip
      pip:
        name: "{{ packages_pip.to_install }}"
      when: "'python2-pip' not in ansible_facts.packages"

    - name: Configurando Serviço NTP
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        mode: 0644
      notify: "Restart NTP service"

    - name: Habilitando os Serviços
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services.to_enabled }}"

    - name: Desabilitando os Serviços
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ services.to_disabled }}"

    - name: Removendo swapfile do /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Desabilitando a swap
      shell: >
        swapoff -a

    - name: Desabilitando o SELinux
      selinux:
        state: disabled

- name: Requísitos para o Kubernetes
  block:
    - name: Verificando se os módulos do kernel foram configurados
      stat:
        path: /etc/modules-load.d/kernel_modules_kubernetes.conf
      register: kernel_modules_kubernetes

    - name: Configurando módulos do kernel
      copy:
        src: kernel_modules_kubernetes.conf
        dest: /etc/modules-load.d/kernel_modules_kubernetes.conf
        owner: root
        group: root
        mode: 0644
      when: (kernel_modules_kubernetes.stat.exists !=  true)

    - name: Verificando se os parametros já foram configurados
      stat:
        path: /etc/sysctl.d/kernel_parameters_kubernetes.conf
      register: kernel_parameters_kubernetes
    
    - name: Parametros de Rede para o Kernel
      copy:
        src: kernel_parameters_kubernetes.conf
        dest: /etc/sysctl.d/kernel_parameters_kubernetes.conf
        owner: root
        group: root
        mode: 0644
      when: (kernel_parameters_kubernetes.stat.exists != true)

    - name: Aplicando os parametros de Rede para o Kernel
      shell: >
        sysctl --system
      args:
        executable: /bin/bash
      register: sysctl_system
      when: 
       - (kernel_parameters_kubernetes.stat.exists != true)
       - (kernel_modules_kubernetes.stat.exists !=  true)