- name: Kubernetes Master
  hosts:
    - masters
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'
  roles:
    - {role: helm, tags: 'helm'}
